using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stefanini.Apoio.AIC.Persistencia.xsd;


namespace Stefanini.Apoio.AIC.Persistencia.Repositorio
{
    public class DiconRepositorio : IDiconRepositorio
    {

        public System.Data.DataTable MontaDataSourceDicon()
        {
            ConsorcioSchema consorcioSchema = new ConsorcioSchema();

            ReportDataSource rds = new ReportDataSource();
            rds.DoDataTable(consorcioSchema.Tables["Comando"]);
            rds.ComColunaDeValor("numcontrato", "657721");
            rds.ComColunaDeValor("dthadesao", "2013-12-11 00:00:00.0");
            rds.ComColunaDeValor("nomcliente", "NANA CLARAs FONSECA SEREJO");
            rds.ComColunaDeValor("desnacionalidade", "BRASILEIRO");
            rds.ComColunaDeValor("staestado", "C");
            rds.ComColunaDeValor("desestadocivil", "CASADA");
            rds.ComColunaDeValor("stasexo", "M");
            rds.ComColunaDeValor("desdocumento", "1234567");
            rds.ComColunaDeValor("nomorgaoemissor", "SSP");
            rds.ComColunaDeValor("numcgccpfcliente", "12345678912");
            rds.ComColunaDeValor("desenderecocobranca", "R");
            rds.ComColunaDeValor("desenderecoresidencial", "QUADRA SQS 203");
            rds.ComColunaDeValor("nombairroresidencial", "ASA SUL");
            rds.ComColunaDeValor("numcepresidencial", "70233090");
            rds.ComColunaDeValor("nomcidaderesidencial", "EMA");
            rds.ComColunaDeValor("nomestadoresidencial", "CE");
            rds.ComColunaDeValor("numdddresidencial", "61");
            rds.ComColunaDeValor("numfonefaxresidencial", "30335580");
            rds.ComColunaDeValor("numcelular", String.Empty);
            rds.ComColunaDeValor("desenderecocomercial", "QUADRA SQS 203");
            rds.ComColunaDeValor("nombairrocomercial", "ASA SUL");
            rds.ComColunaDeValor("numcepcomercial", "70233090");
            rds.ComColunaDeValor("nomcidadecomercial", "EMA");
            rds.ComColunaDeValor("nomestadocomercial", "CE");
            rds.ComColunaDeValor("numdddcomercial", "61");
            rds.ComColunaDeValor("numfonefaxcomercial", "33264373");
            rds.ComColunaDeValor("descomplementocomercial", "BLOCO I AP");
            rds.ComColunaDeValor("desenderecooutro", String.Empty);
            rds.ComColunaDeValor("nombairrooutro", String.Empty);
            rds.ComColunaDeValor("numcepoutro", String.Empty);
            rds.ComColunaDeValor("nomcidadeoutro", String.Empty);
            rds.ComColunaDeValor("nomestadooutro", String.Empty);
            rds.ComColunaDeValor("numdddoutro", String.Empty);
            rds.ComColunaDeValor("numfonefaxoutro", String.Empty);
            rds.ComColunaDeValor("descomplementooutro", String.Empty);
            rds.ComColunaDeValor("desemail", String.Empty);
            rds.ComColunaDeValor("despessoa", "F");
            rds.ComColunaDeValor("dthdatanascimento", "1982-01-01 00:00:00.0");
            rds.ComColunaDeValor("codnivelensino", "4");
            rds.ComColunaDeValor("desnivelensino", "Ensino Superior");
            rds.ComColunaDeValor("stasigilo", "N");
            rds.ComColunaDeValor("numprazo", "69");
            rds.ComColunaDeValor("pcttaxaadministracao", "14.0");
            rds.ComColunaDeValor("pctfundoreserva", "3.0");
            rds.ComColunaDeValor("pctadesao", "1.0");
            rds.ComColunaDeValor("pctideal", "1.4286");
            rds.ComColunaDeValor("nomcidadelocalidade", String.Empty);
            rds.ComColunaDeValor("nomestadolocalidade", String.Empty);
            rds.ComColunaDeValor("codbem", "AN0100");
            rds.ComColunaDeValor("desbem", "AUTO CREDITO 100MIL");
            rds.ComColunaDeValor("inddebitoconta", "0065772112345678912");
            rds.ComColunaDeValor("codlinhadigitavel_01", "10498");
            rds.ComColunaDeValor("codlinhadigitavel_02", "22081");
            rds.ComColunaDeValor("codlinhadigitavel_03", "45125");
            rds.ComColunaDeValor("codlinhadigitavel_04", "063086");
            rds.ComColunaDeValor("codlinhadigitavel_05", "70000");
            rds.ComColunaDeValor("codlinhadigitavel_06", "002462");
            rds.ComColunaDeValor("codlinhadigitavel_07", "8");
            rds.ComColunaDeValor("codlinhadigitavel_08", "59100000194570");
            rds.ComColunaDeValor("desnossonumero", "8220845125-5");
            rds.ComColunaDeValor("codlinhadigitavel", "10498.22081  45125.063086  70000.002462 8  59100000194570");
            rds.ComColunaDeValor("codbarra", "10498591000001945708220845125063087000000246");
            rds.ComColunaDeValor("desresposta001", String.Empty);
            rds.ComColunaDeValor("desobservacao001", String.Empty);
            rds.ComColunaDeValor("desresposta002", String.Empty);
            rds.ComColunaDeValor("desobservacao002", String.Empty);
            rds.ComColunaDeValor("desresposta003", String.Empty);
            rds.ComColunaDeValor("desobservacao003", String.Empty);
            rds.ComColunaDeValor("desresposta004", String.Empty);
            rds.ComColunaDeValor("desobservacao004", String.Empty);
            rds.ComColunaDeValor("desresposta005", String.Empty);
            rds.ComColunaDeValor("desobservacao005", String.Empty);
            rds.ComColunaDeValor("desresposta006", String.Empty);
            rds.ComColunaDeValor("desobservacao006", String.Empty);
            rds.ComColunaDeValor("desproximaassembleia", "23/12/2013");
            rds.ComColunaDeValor("dthprimeiraassembleia", "23/12/2013");
            rds.ComColunaDeValor("codtipovenda", "997");
            rds.ComColunaDeValor("codtipogrupo", "ANG");
            rds.ComColunaDeValor("desprofissao", "Leiloeiro e afins");
            rds.ComColunaDeValor("vlrrenda", "4500.01");
            rds.ComColunaDeValor("numcaixapostalresidencial", String.Empty);
            rds.ComColunaDeValor("numcaixapostalcomercial", String.Empty);
            rds.ComColunaDeValor("destipobem", "Móvel");
            rds.ComColunaDeValor("vlrbem", "100000.0");
            rds.ComColunaDeValor("desfabricante", "AUTO");
            rds.ComColunaDeValor("pctseguro", "0.068");
            rds.ComColunaDeValor("pctsegquebra", "0.0");
            rds.ComColunaDeValor("nummaximoparticipantes", "1000");
            rds.ComColunaDeValor("dthvencimento", "2013-12-12 00:00:00.0");
            rds.ComColunaDeValor("desformapagamento", "BB");
            rds.ComColunaDeValor("numautorizacao", String.Empty);
            rds.ComColunaDeValor("numautorizacaofr", "0");
            rds.ComColunaDeValor("codbancopagamento", "104");
            rds.ComColunaDeValor("codcontapagamento", String.Empty);
            rds.ComColunaDeValor("vlrpagamento", "1945.7");
            rds.ComColunaDeValor("dthcompensacaopagamento", "2013-12-11 00:00:00.0");
            rds.ComColunaDeValor("codbarradocumentos", String.Empty);
            rds.ComColunaDeValor("desoptanteseguro", "S");
            rds.ComColunaDeValor("descarteira", "8");
            rds.ComColunaDeValor("codoperacao", String.Empty);
            rds.ComColunaDeValor("codbancoenc", "0");
            rds.ComColunaDeValor("numagencia", "0");
            rds.ComColunaDeValor("numdigitoagencia", String.Empty);
            rds.ComColunaDeValor("numcontacorrente", String.Empty);
            rds.ComColunaDeValor("numdigitoconta", String.Empty);
            rds.ComColunaDeValor("codusuarioindicador", "0");
            rds.ComColunaDeValor("nomusuarioindicador", String.Empty);
            rds.ComColunaDeValor("numdiavencimentogrupo", "15");
            rds.ComColunaDeValor("numdiavencimentoproposta", "12");
            rds.ComColunaDeValor("pctsegvida", "0.068");
            rds.ComColunaDeValor("vlrcreditoinicial", "90000.0");
            rds.ComColunaDeValor("vlrcreditofinal", "150000.0");
            rds.ComColunaDeValor("vlrparcelainicialpi", "1.0");
            rds.ComColunaDeValor("vlrparcelafinalpf", "1.0");
            rds.ComColunaDeValor("vlrtaxaadministracaopipf", "0.4024");
            rds.ComColunaDeValor("vlrtaxaadministracaodemaisparc", "0.1691");
            rds.ComColunaDeValor("vlrfundocomumpipf", "1.2498");
            rds.ComColunaDeValor("vlrfundocomumdemaisparc", "1.4831");
            rds.ComColunaDeValor("vlrfundoreservapipf", "0.0435");
            rds.ComColunaDeValor("vlrfundoreservademaisparc", "0.0435");
            rds.ComColunaDeValor("vlramortizacaopipf", "1.6957");
            rds.ComColunaDeValor("vlramortizacaodemaisparc", "1.6957");
            rds.ComColunaDeValor("codigoconvenio", String.Empty);
            rds.ComColunaDeValor("codigo_banco", String.Empty);
            rds.ComColunaDeValor("codigo_operacao_1_parcela", "0");
            rds.ComColunaDeValor("codigo_banco_1_parcela", "0");
            rds.ComColunaDeValor("numero_agencia_1_parcela", String.Empty);
            rds.ComColunaDeValor("digito_agencia_1_parcela", String.Empty);
            rds.ComColunaDeValor("numero_conta_corrente_1_parcela", String.Empty);
            rds.ComColunaDeValor("digito_conta_1_parcela", String.Empty);
            rds.ComColunaDeValor("codigo_operacao_enc", "001");
            rds.ComColunaDeValor("codigo_banco_enc", "33");
            rds.ComColunaDeValor("numero_agencia_enc", "1203");
            rds.ComColunaDeValor("digito_agencia_enc", "0");
            rds.ComColunaDeValor("numero_conta_corrente_enc", "120374");
            rds.ComColunaDeValor("digito_conta_enc", "0");
            rds.ComColunaDeValor("staemiteboletocobranca", String.Empty);
            rds.ComColunaDeValor("staemiteboletoparcela", String.Empty);
            rds.ComColunaDeValor("staemiteboletoadesao", String.Empty);
            rds.ComColunaDeValor("staregistrarecebimento", String.Empty);
            rds.ComColunaDeValor("stainformagrupocota", String.Empty);
            rds.ComColunaDeValor("vlrparcela", String.Empty);
            rds.ComColunaDeValor("vlradesao", String.Empty);
            rds.ComColunaDeValor("numplanocota", String.Empty);
            rds.ComColunaDeValor("codgrupo", String.Empty);
            rds.ComColunaDeValor("codcota", String.Empty);
            rds.ComColunaDeValor("desversao", String.Empty);
            rds.ComColunaDeValor("codagentecobrancaprop", String.Empty);
            rds.ComColunaDeValor("codagentecobrancaout", String.Empty);
            rds.ComColunaDeValor("codagente", String.Empty);
            rds.ComColunaDeValor("desagenteprop", String.Empty);
            rds.ComColunaDeValor("codcedente", String.Empty);
            rds.ComColunaDeValor("numaviso", String.Empty);
            rds.ComColunaDeValor("vlrcobranca", String.Empty);
            rds.ComColunaDeValor("codbancoagente", String.Empty);
            rds.ComColunaDeValor("numparcela", String.Empty);
            rds.ComColunaDeValor("desidentificadorbancario", String.Empty);
            rds.ComColunaDeValor("numnossonumero", String.Empty);
            rds.ComColunaDeValor("coddigitavel", String.Empty);
            rds.ComColunaDeValor("dessacado1", String.Empty);
            rds.ComColunaDeValor("dessacado2", String.Empty);
            rds.ComColunaDeValor("numdiasparavencimentopropos", String.Empty);
            rds.ComColunaDeValor("stautilizatarifabancaria", String.Empty);
            rds.ComColunaDeValor("stautilizatarifabancariacota", String.Empty);
            rds.ComColunaDeValor("vlrtarifabancaria", String.Empty);
            rds.ComColunaDeValor("nomconsorciadocontemplado", String.Empty);
            return rds.ObtemReportDataSource();
        }
    }
}
